package com.happybaby.happybaby.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.happybaby.happybaby.greendao.ShoppingCartBean;
import com.happybaby.happybaby.search.MyData;

import com.happybaby.happybaby.greendao.ShoppingCartBeanDao;
import com.happybaby.happybaby.greendao.MyDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shoppingCartBeanDaoConfig;
    private final DaoConfig myDataDaoConfig;

    private final ShoppingCartBeanDao shoppingCartBeanDao;
    private final MyDataDao myDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shoppingCartBeanDaoConfig = daoConfigMap.get(ShoppingCartBeanDao.class).clone();
        shoppingCartBeanDaoConfig.initIdentityScope(type);

        myDataDaoConfig = daoConfigMap.get(MyDataDao.class).clone();
        myDataDaoConfig.initIdentityScope(type);

        shoppingCartBeanDao = new ShoppingCartBeanDao(shoppingCartBeanDaoConfig, this);
        myDataDao = new MyDataDao(myDataDaoConfig, this);

        registerDao(ShoppingCartBean.class, shoppingCartBeanDao);
        registerDao(MyData.class, myDataDao);
    }
    
    public void clear() {
        shoppingCartBeanDaoConfig.clearIdentityScope();
        myDataDaoConfig.clearIdentityScope();
    }

    public ShoppingCartBeanDao getShoppingCartBeanDao() {
        return shoppingCartBeanDao;
    }

    public MyDataDao getMyDataDao() {
        return myDataDao;
    }

}
